### ISSUE TITLE
Common location for images and icon

### ISSUE THREAD

**Issue by Kampi** [jakkra/ZSWatch#153]
- Should be placed in the external flash
- Should prevent fragmentation and double images to save space
- QSPI preferred (how do we want to handle the "normal" SPI?)

**Comment by jakkra** [comment]
Need to experiment a bit with v4 and QSPI, if we can put everything in external it would be great.
For v3 I'm not sure exactly how to handle it as stuff on watchface must be in internal flash, otherwise it's too slow.

Will think abit about what's the best approach. 

Also another issue is that some of the .c images files I don't know the source of, and they need to be converted to .bin to work in external flash. So will need some thinking.

**Comment by Kampi** [comment]
I think it's enough to think about how to implement it in rev 4 with all the infrastructure. A Backport to rev 3 can be done later if there is a need to do it. For now it looks okay 👍
